// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopizer-security.proto

package com.salesmanager.shop.security.v2.api.grpc;

public final class ServiceDiscoveryOuter {
  private ServiceDiscoveryOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shopizer_security_ReadablePermission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shopizer_security_ReadablePermission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shopizer_security_ReadableGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shopizer_security_ReadableGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shopizer_security_GroupNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shopizer_security_GroupNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shopizer_security_ReadablePermissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shopizer_security_ReadablePermissionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shopizer_security_ReadableGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shopizer_security_ReadableGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shopizer_security_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shopizer_security_EmptyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027shopizer-security.proto\022\021shopizer.secu" +
      "rity\".\n\022ReadablePermission\022\n\n\002id\030\001 \001(\t\022\014" +
      "\n\004name\030\002 \001(\t\"7\n\rReadableGroup\022\n\n\002id\030\001 \001(" +
      "\t\022\014\n\004name\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\" \n\020GroupNa" +
      "meRequest\022\014\n\004name\030\001 \001(\t\"X\n\032ReadablePermi" +
      "ssionResponse\022:\n\013permissions\030\001 \003(\0132%.sho" +
      "pizer.security.ReadablePermission\"I\n\025Rea" +
      "dableGroupResponse\0220\n\006groups\030\001 \003(\0132 .sho" +
      "pizer.security.ReadableGroup\"\016\n\014EmptyReq" +
      "uest2\256\002\n\013SecurityApi\022g\n\017listPermissions\022" +
      "#.shopizer.security.GroupNameRequest\032-.s" +
      "hopizer.security.ReadablePermissionRespo" +
      "nse\"\000\022_\n\013permissions\022\037.shopizer.security" +
      ".EmptyRequest\032-.shopizer.security.Readab" +
      "lePermissionResponse\"\000\022U\n\006groups\022\037.shopi" +
      "zer.security.EmptyRequest\032(.shopizer.sec" +
      "urity.ReadableGroupResponse\"\000BE\n*com.sal" +
      "esmanager.shop.security.v2.api.grpcB\025Ser" +
      "viceDiscoveryOuterP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_shopizer_security_ReadablePermission_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_shopizer_security_ReadablePermission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shopizer_security_ReadablePermission_descriptor,
        new String[] { "Id", "Name", });
    internal_static_shopizer_security_ReadableGroup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_shopizer_security_ReadableGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shopizer_security_ReadableGroup_descriptor,
        new String[] { "Id", "Name", "Type", });
    internal_static_shopizer_security_GroupNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_shopizer_security_GroupNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shopizer_security_GroupNameRequest_descriptor,
        new String[] { "Name", });
    internal_static_shopizer_security_ReadablePermissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_shopizer_security_ReadablePermissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shopizer_security_ReadablePermissionResponse_descriptor,
        new String[] { "Permissions", });
    internal_static_shopizer_security_ReadableGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_shopizer_security_ReadableGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shopizer_security_ReadableGroupResponse_descriptor,
        new String[] { "Groups", });
    internal_static_shopizer_security_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_shopizer_security_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shopizer_security_EmptyRequest_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
