// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopizer-security.proto

package com.salesmanager.shop.security.v2.api.proto;

public interface EmptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shopizer.security.EmptyRequest)
    com.google.protobuf.MessageOrBuilder {
}
