// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopizer-security.proto

package com.salesmanager.shop.security.v2.api.proto;

public interface ReadablePermissionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shopizer.security.ReadablePermissionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .shopizer.security.ReadablePermission permissions = 1;</code>
   */
  java.util.List<ReadablePermission>
      getPermissionsList();
  /**
   * <code>repeated .shopizer.security.ReadablePermission permissions = 1;</code>
   */
  ReadablePermission getPermissions(int index);
  /**
   * <code>repeated .shopizer.security.ReadablePermission permissions = 1;</code>
   */
  int getPermissionsCount();
  /**
   * <code>repeated .shopizer.security.ReadablePermission permissions = 1;</code>
   */
  java.util.List<? extends ReadablePermissionOrBuilder>
      getPermissionsOrBuilderList();
  /**
   * <code>repeated .shopizer.security.ReadablePermission permissions = 1;</code>
   */
  ReadablePermissionOrBuilder getPermissionsOrBuilder(
      int index);
}
