package com.salesmanager.shop.entity;

import java.util.Date;

public class Language {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGUAGE.LANGUAGE_ID
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    private Integer LANGUAGE_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGUAGE.DATE_CREATED
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    private Date DATE_CREATED;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGUAGE.DATE_MODIFIED
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    private Date DATE_MODIFIED;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGUAGE.UPDT_ID
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    private String UPDT_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGUAGE.CODE
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    private String CODE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGUAGE.SORT_ORDER
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    private Integer SORT_ORDER;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGUAGE.LANGUAGE_ID
     *
     * @return the value of LANGUAGE.LANGUAGE_ID
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public Integer getLANGUAGE_ID() {
        return LANGUAGE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGUAGE.LANGUAGE_ID
     *
     * @param LANGUAGE_ID the value for LANGUAGE.LANGUAGE_ID
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public void setLANGUAGE_ID(Integer LANGUAGE_ID) {
        this.LANGUAGE_ID = LANGUAGE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGUAGE.DATE_CREATED
     *
     * @return the value of LANGUAGE.DATE_CREATED
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGUAGE.DATE_CREATED
     *
     * @param DATE_CREATED the value for LANGUAGE.DATE_CREATED
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGUAGE.DATE_MODIFIED
     *
     * @return the value of LANGUAGE.DATE_MODIFIED
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGUAGE.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for LANGUAGE.DATE_MODIFIED
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGUAGE.UPDT_ID
     *
     * @return the value of LANGUAGE.UPDT_ID
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public String getUPDT_ID() {
        return UPDT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGUAGE.UPDT_ID
     *
     * @param UPDT_ID the value for LANGUAGE.UPDT_ID
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public void setUPDT_ID(String UPDT_ID) {
        this.UPDT_ID = UPDT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGUAGE.CODE
     *
     * @return the value of LANGUAGE.CODE
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public String getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGUAGE.CODE
     *
     * @param CODE the value for LANGUAGE.CODE
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public void setCODE(String CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGUAGE.SORT_ORDER
     *
     * @return the value of LANGUAGE.SORT_ORDER
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public Integer getSORT_ORDER() {
        return SORT_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGUAGE.SORT_ORDER
     *
     * @param SORT_ORDER the value for LANGUAGE.SORT_ORDER
     *
     * @mbg.generated Sun Jul 30 20:50:06 GMT+08:00 2023
     */
    public void setSORT_ORDER(Integer SORT_ORDER) {
        this.SORT_ORDER = SORT_ORDER;
    }
}