// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopizer-security.proto

package com.salesmanager.shop.security.v2.api.grpc;

public interface ReadableGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shopizer.security.ReadableGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
